version: '3.8'

services:
  web:
    build: .
    command: uvicorn shortener_app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./shortener.db:/app/shortener.db
    expose:
      - "5432" # adjust this if needed
